<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuBaruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Animasi BS Kelas XI dan XII',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Animasi_BS_Kelas_XI_dan_XII_Cover.png',
                'pdf_path' => 'buku/pdf/Animasi_BS_XI_dan_XII (1).pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dasar Teknik Konstruksi Kapal Semester 2 KLS X',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Dasar-Teknik-Konstruksi-Kapal-Semester-2-BS-KLS-X-Cover.png',
                'pdf_path' => 'buku/pdf/Dasar-Teknik-Konstruksi-Kapal-Semester-2-BS-KLS-X (1).pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ekonomi Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/ekonimi_kls_XI.jpeg',
                'pdf_path' => 'buku/pdf/Ekonomi_BG_KLS_XI_Rev_2.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Indonesia Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/indonesia_BG_kls_XI.jpeg',
                'pdf_path' => 'buku/pdf/Indonesia_BG_KLS_XI_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Informatika Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Informatika_kls_11.jpeg',
                'pdf_path' => 'buku/pdf/Informatika_BG_KLS_XI_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pendidikan Agama Islam Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/islam_BG_kls_XI.jpeg',
                'pdf_path' => 'buku/pdf/Islam-BG-KLS-XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Jepang Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/BahasaJepang.jpeg',
                'pdf_path' => 'buku/pdf/Jepang_BG_KLS_XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'KKA Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/KKA_BS_KLS_11_Cover.png',
                'pdf_path' => 'buku/pdf/KKA_BS_KLS_11.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kuliner Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Kuliner_BS_KLS_XI.jpeg',
                'pdf_path' => 'buku/pdf/Kuliner_BS_KLS_XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Layanan Penunjang Keperawatan dan Caregiving Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Layanan_Penunjang_Keperawatan_dan_Caregiving_BS_Kelas_XI.jpeg',
                'pdf_path' => 'buku/pdf/Layanan_Penunjang_Keperawatan_dan_Caregiving_BS_Kelas_XI_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Mandarin Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Mandarin_BG_XI.jpeg',
                'pdf_path' => 'buku/pdf/Mandarin_BG_XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nautika Kapal Niaga Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Nautika_kapal_niaga_kls_XI.jpeg',
                'pdf_path' => 'buku/pdf/Nautika_Kapal_Niaga_BG_KLS_XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'PJOK Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/PJOK_kls_BG_XI.jpeg',
                'pdf_path' => 'buku/pdf/PJOK_BS_KLS_XI.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengembangan Gim BG Kelas XI XII',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Pengembangan_Gim_BG_KLS_XI_XII_Cover.png',
                'pdf_path' => 'buku/pdf/Pengembangan_Gim_BG_KLS_XI_XII.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pengembangan Gim BS Kelas XI XII',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Pengembangan_Gim_BS_KLS_XI_XII_Cover.png',
                'pdf_path' => 'buku/pdf/Pengembangan_Gim_BS_KLS_XI_XII.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sejarah Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Sejarah_BS_Kelas_XI_Rev_Cover.png',
                'pdf_path' => 'buku/pdf/Sejarah_BS_Kelas_XI_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seni Musik Kelas XI',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/seni_musik_BG_kls_XI.jpeg',
                'pdf_path' => 'buku/pdf/Seni_Musik_BG_KLS_XI_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seni Tari Kelas X',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/Seni_Tari_BG_KLS_X_Rev_Cover.png',
                'pdf_path' => 'buku/pdf/Seni_Tari_BG_KLS_X_Rev.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Teknik Energi Surya Hidro dan Angin Kelas X',
                'author' => 'Kemdikbud',
                'category' => 'Buku Sekolah',
                'rack' => 'Rak 1',
                'type' => 'both',
                'stock' => 50,
                'cover_image_url' => 'buku/sampul/teknik_tenaga_surya.jpeg',
                'pdf_path' => 'buku/pdf/Teknik_Energi_Surya_Hidro_dan_Angin_BS_Kelas_X.pdf',
                'rating' => 0.0,
                'popularity_score' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('books')->insert($books);
    }
}
